service: halcyon-client

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-west-1
    environment:
        REACT_APP_GRAPHQL_URL: ${cf:halcyon-api-${opt:stage, self:provider.stage}.ServiceEndpoint, ''}

plugins:
    - serverless-build-client
    - serverless-s3-sync

custom:
    s3Sync:
        - bucketNameKey: ClientBucketOutputKey
          localDir: build
          deleteRemoved: true

resources:
    Resources:
        ClientBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: halcyon-client-${opt:stage, self:provider.stage}
                
    Outputs:
        ClientBucketOutputKey:
            Value: !Ref ClientBucket
