name: halcyon

services:
    halcyon:
        image: halcyon:dev
        build:
            context: .
            target: dev
        command: npm run dev -- --host=0.0.0.0 --port=5173
        environment:
            USE_POLLING: true
            VITE_API_URL: http://localhost:5257
        ports:
            - 5173:5173
        volumes:
            - ./src:/app/src
            - ./public:/app/public

    halcyon-api:
        image: ghcr.io/chrispoulter/halcyon-api:latest
        environment:
            ConnectionStrings__Database: Host=host.docker.internal;Port=5432;Database=halcyon-api;Username=postgres;Password=password
            ConnectionStrings__Mail: Endpoint=smtp://host.docker.internal:1025
            Logging__LogLevel__Microsoft.AspNetCore.DataProtection: Error
        ports:
            - 5257:8080
            - 7257:8081
        restart: always
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:17.2
        user: postgres
        environment:
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: always
        healthcheck:
            test: [ 'CMD', 'pg_isready' ]
            interval: 10s
            timeout: 5s
            retries: 3

    maildev:
        image: maildev/maildev:2.1.0
        environment:
            MAILDEV_MAIL_DIRECTORY: /tmp
        ports:
            - 1025:1025
            - 1080:1080
        volumes:
            - maildev:/tmp
        restart: always

volumes:
    postgres:
        name: halcyon-postgres
    maildev:
        name: halcyon-maildev
