service: halcyon

useDotenv: true

provider:
    name: aws
    runtime: nodejs12.x
    stage: local
    region: eu-west-1
    memorySize: 1024
    logRetentionInDays: 3
    apiGateway:
        shouldStartNameWithService: true
    lambdaHashingVersion: 20201221
    environment:
        ENVIRONMENT: ${env:ENVIRONMENT, ''}
        RELEASE: ${env:RELEASE, ''}
        CLIENT_URL: ${env:CLIENT_URL, self:custom.s3.client.url.${self:custom.stage}, self:custom.s3.client.url.default}
        SNS_ENDPOINT: ${self:custom.sns.endpoint.${self:custom.stage}, self:custom.sns.endpoint.default}
        SNS_EVENTSARN: ${self:custom.sns.events.arn}
        FAUNADB_SECRET: ${env:FAUNADB_SECRET, ''}
        JWT_SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
        JWT_AUDIENCE: ${env:JWT_AUDIENCE, ''}
        JWT_ISSUER: ${env:JWT_ISSUER, ''}
        JWT_EXPIRESIN: ${env:JWT_EXPIRESIN, ''}
        MAILGUN_DOMAIN: ${env:MAILGUN_DOMAIN, ''}
        MAILGUN_APIKEY: ${env:MAILGUN_APIKEY, ''}
        MAILGUN_NOREPLY: ${env:MAILGUN_NOREPLY, ''}
        SEED_EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
        SEED_PASSWORD: ${env:SEED_PASSWORD, ''}
        SENTRY_DSN: ${env:SENTRY_DSN, ''}
    iam:
        role:
            statements:
                - Effect: Allow
                  Action:
                      - sns:*
                  Resource:
                      - ${self:custom.sns.events.arn}

package:
    individually: true

plugins:
    - serverless-pseudo-parameters
    - serverless-webpack
    - serverless-offline
    - serverless-offline-sns
    - serverless-build-client
    - serverless-s3-sync

functions:
    events:
        handler: api/eventHandlers/index.handler
        events:
            - sns:
                  arn: ${self:custom.sns.events.arn}
                  topicName: ${self:custom.sns.events.topicName}

    app:
        handler: api/index.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: ${self:custom.cors}
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: ${self:custom.cors}

custom:
    accountId: '#{AWS::AccountId}'
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}
    prefix: ${self:service}-${self:custom.stage}

    cors:
        origin: '*'
        headers: '*'
        allowCredentials: true

    s3:
        client:
            bucket: ${self:custom.prefix}
            url:
                default: http://${self:custom.s3.client.bucket}.s3-website-${self:custom.region}.amazonaws.com
                local: http://localhost:3000

    sns:
        events:
            topicName: ${self:custom.prefix}-events
            arn: arn:aws:sns:${self:custom.region}:${self:custom.accountId}:${self:custom.sns.events.topicName}
        endpoint:
            default: null
            local: http://127.0.0.1:4002

    endpoints:
        graphQL: $cf:${self:custom.prefix}.ServiceEndpoint}

    serverless-offline:
        httpPort: 3001
        noPrependStageInUrl: true

    serverless-offline-sns:
        port: 4002
        debug: true

    buildClient:
        environment:
            REACT_APP_ENVIRONMENT: ${env:ENVIRONMENT, ''}
            REACT_APP_RELEASE: ${env:RELEASE, ''}
            REACT_APP_SENTRY_DSN: ${env:SENTRY_DSN, ''}
            REACT_APP_GA_MEASUREMENTID: ${env:GA_MEASUREMENTID, ''}
            REACT_APP_GRAPHQL_URL: ${env:GRAPHQL_URL, self:custom.endpoints.graphQL}

    s3Sync:
        - bucketNameKey: ClientBucketOutputKey
          localDir: build
          deleteRemoved: true
          acl: public-read

resources:
    Resources:
        EventsSnsTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: ${self:custom.sns.events.topicName}

        ClientBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.s3.client.bucket}
                AccessControl: PublicRead
                WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: index.html

    Outputs:
        ClientBucketOutputKey:
            Value: !Ref ClientBucket
