service: halcyon

useDotenv: true

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-west-1
    memorySize: 1024
    logRetentionInDays: 3
    apiGateway:
        shouldStartNameWithService: true
    environment:
        ENVIRONMENT: ${env:ENVIRONMENT, ''}
        RELEASE: ${env:RELEASE, ''}
        FAUNADB_SECRET: ${env:FAUNADB_SECRET, ''}
        JWT_SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
        JWT_AUDIENCE: ${env:JWT_AUDIENCE, ''}
        JWT_ISSUER: ${env:JWT_ISSUER, ''}
        JWT_EXPIRESIN: ${env:JWT_EXPIRESIN, ''}
        MAILGUN_DOMAIN: ${env:MAILGUN_DOMAIN, ''}
        MAILGUN_APIKEY: ${env:MAILGUN_APIKEY, ''}
        MAILGUN_NOREPLY: ${env:MAILGUN_NOREPLY, ''}
        SEED_EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
        SEED_PASSWORD: ${env:SEED_PASSWORD, ''}
        SENTRY_DSN: ${env:SENTRY_DSN, ''}
        SNS_SENDEMAIL: ${self:custom.sns.sendEmail.arn}
    iamRoleStatements:
        - Effect: Allow
          Action:
              - sns:Publish
          Resource:
              - arn:aws:sns:${self:custom.region}:#{AWS::AccountId}:${self:custom.sns.sendEmail.topicName}

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-offline-sns
    - serverless-build-client
    - serverless-s3-sync

functions:
    sendEmail:
        handler: api/handlers/sendEmail.handler
        events:
            - sns:
                  arn: ${self:custom.sns.sendEmail.arn}
                  topicName: ${self:custom.sns.sendEmail.topicName}

    app:
        handler: api/index.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: ${self:custom.cors}
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors: ${self:custom.cors}

custom:
    stage: ${opt:stage, self:provider.stage}
    region: ${opt:region, self:provider.region}

    cors:
        origin: '*'
        headers: '*'
        allowCredentials: true

    s3:
        client: ${self:service}-${self:custom.stage}

    sns:
        sendEmail:
            topicName: ${self:service}-${self:custom.stage}-sendEmail
            arn: 'arn:aws:sns:${self:custom.region}:${AWS::AccountId}:${self:custom.sns.sendEmail.topicName}'

    endpoints:
        graphQL: ${cf:${self:service}-${self:custom.stage}.ServiceEndpoint, ''}

    serverless-offline:
        httpPort: 3001
        noPrependStageInUrl: true

    serverless-offline-sns:
        port: 4002
        debug: true

    buildClient:
        environment:
            REACT_APP_ENVIRONMENT: ${env:ENVIRONMENT, ''}
            REACT_APP_RELEASE: ${env:RELEASE, ''}
            REACT_APP_SENTRY_DSN: ${env:SENTRY_DSN, ''}
            REACT_APP_GA_MEASUREMENTID: ${env:GA_MEASUREMENTID, ''}
            REACT_APP_GRAPHQL_URL: ${self:custom.endpoints.graphQL}

    s3Sync:
        - bucketNameKey: ClientBucketOutputKey
          localDir: build
          deleteRemoved: true
          acl: public-read

resources:
    Resources:
        SendEmailSnsTopic:
            Type: AWS::SNS::Topic
            Properties:
                TopicName: ${self:custom.sns.sendEmail.topicName}

        ClientBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:custom.s3.client}
                AccessControl: PublicRead
                WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: index.html

    Outputs:
        ClientBucketOutputKey:
            Value: !Ref ClientBucket
