service: halcyon-graphql

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-west-1
    memorySize: 1024
    logRetentionInDays: 3
    environment:
        MONGODB_URI: ${env:MONGODB_URI, ''}
        JWT_SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
        JWT_AUDIENCE: ${env:JWT_AUDIENCE, ''}
        JWT_ISSUER: ${env:JWT_ISSUER, ''}
        MAILGUN_DOMAIN: ${env:MAILGUN_DOMAIN, ''}
        MAILGUN_PASSWORD: ${env:MAILGUN_PASSWORD, ''}
        MAILGUN_NOREPLY: ${env:MAILGUN_NOREPLY, ''}
        SEED_EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
        SEED_PASSWORD: ${env:SEED_PASSWORD, ''}

plugins:
    - serverless-offline
    - serverless-dotenv-plugin

functions:
    app:
        handler: src/serverless.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors: true
            - http:
                  path: '{proxy+}'
                  method: ANY
                  cors: true

custom:
    serverless-offline:
        port: 4000
