service: halcyon

useDotenv: true

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-west-1
    memorySize: 1024
    logRetentionInDays: 3
    apiGateway:
        shouldStartNameWithService: true
    environment:
        ENVIRONMENT: ${env:ENVIRONMENT, ''}
        RELEASE: ${env:RELEASE, ''}
        FAUNADB_SECRET: ${env:FAUNADB_SECRET, ''}
        JWT_SECURITYKEY: ${env:JWT_SECURITYKEY, ''}
        JWT_AUDIENCE: ${env:JWT_AUDIENCE, ''}
        JWT_ISSUER: ${env:JWT_ISSUER, ''}
        JWT_EXPIRESIN: ${env:JWT_EXPIRESIN, ''}
        MAILGUN_DOMAIN: ${env:MAILGUN_DOMAIN, ''}
        MAILGUN_APIKEY: ${env:MAILGUN_APIKEY, ''}
        MAILGUN_NOREPLY: ${env:MAILGUN_NOREPLY, ''}
        SEED_EMAILADDRESS: ${env:SEED_EMAILADDRESS, ''}
        SEED_PASSWORD: ${env:SEED_PASSWORD, ''}
        SENTRY_DSN: ${env:SENTRY_DSN, ''}

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-build-client
    - serverless-s3-sync

functions:
    app:
        handler: api/index.handler
        events:
            - http:
                  path: /
                  method: ANY
                  cors:
                      origin: '*'
                      headers: '*'
                      allowCredentials: true
            - http:
                  path: /{proxy+}
                  method: ANY
                  cors:
                      origin: '*'
                      headers: '*'
                      allowCredentials: true

custom:
    serverless-offline:
        httpPort: 3001
        noPrependStageInUrl: true

    buildClient:
        environment:
            REACT_APP_ENVIRONMENT: ${env:ENVIRONMENT, ''}
            REACT_APP_RELEASE: ${env:RELEASE, ''}
            REACT_APP_SENTRY_DSN: ${env:SENTRY_DSN, ''}
            REACT_APP_GRAPHQL_URL: ${cf:${self:service}-${opt:stage, self:provider.stage}.ServiceEndpoint, ''}

    s3Sync:
        - bucketNameKey: ClientBucketOutputKey
          localDir: build
          deleteRemoved: true
          acl: public-read

resources:
    Resources:
        ClientBucket:
            Type: AWS::S3::Bucket
            Properties:
                BucketName: ${self:service}-${opt:stage, self:provider.stage}
                AccessControl: PublicRead
                WebsiteConfiguration:
                    IndexDocument: index.html
                    ErrorDocument: index.html

    Outputs:
        ClientBucketOutputKey:
            Value: !Ref ClientBucket
