name: CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: 5.x

            - name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.7
              with:
                  useConfigFile: true

            - name: Set Environment Variables
              run: |
                  echo "REACT_APP_VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV
                  echo "REACT_APP_STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV

            - name: Docker Login
              uses: azure/docker-login@v1
              with:
                  login-server: halcyon.azurecr.io
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build
              run: |
                  yarn version --new-version ${{ env.REACT_APP_VERSION }} --no-git-tag-version
                  docker build . -t halcyon.azurecr.io/halcyon:${{ env.REACT_APP_VERSION }}
                  docker push halcyon.azurecr.io/halcyon:${{ env.REACT_APP_VERSION }}

            - name: Azure Login
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Create Resource Group
              run: |
                  az group create \
                    --name "halcyon-${{ env.REACT_APP_STAGE }}" \
                    --location "${{ secrets.AZURE_LOCATION }}"

            - name: Deploy ARM Template
              uses: azure/arm-deploy@v1
              with:
                  resourceGroupName: halcyon-${{ env.REACT_APP_STAGE }}
                  template: ./azuredeploy.json
                  parameters: stage="${{ env.REACT_APP_STAGE }}"
                      dbhost="${{ secrets.DB_HOST }}"
                      dbUser="${{ secrets.DB_USER }}"
                      dbPassword="${{ secrets.DB_PASSWORD }}"
                      dbDatabase="halcyon-${{ secrets.REACT_APP_STAGE }}-db"
                      emailSmtpServer="${{ secrets.EMAIL_SMTP_SERVER }}"
                      emailSmtpPort="${{ secrets.EMAIL_SMTP_PORT }}"
                      emailSmtpUserName="${{ secrets.EMAIL_SMTP_USERNAME }}"
                      emailSmtpPassword="${{ secrets.EMAIL_SMTP_PASSWORD }}"
                      emailNoReplyAddress="${{ secrets.EMAIL_NO_REPLY_ADDRESS }}"
                      jwtSecurityKey="${{ secrets.JWT_SECURITY_KEY }}"
                      jwtIssuer="${{ secrets.JWT_ISSUER }}"
                      jwtAudience="${{ secrets.JWT_AUDIENCE }}"
                      jwtExpiresIn="${{ secrets.JWT_EXPIRES_IN }}"
                      seedEmailAddress="${{ secrets.SEED_EMAIL_ADDRESS }}"
                      seedPassword="${{ secrets.SEED_PASSWORD }}"

            - name: Deploy
              uses: azure/webapps-deploy@v2
              with:
                  app-name: halcyon-${{ env.REACT_APP_STAGE }}-web
                  images: 'halcyon.azurecr.io/halcyon:${{ env.REACT_APP_VERSION }}'

            - name: Azure Logout
              run: |
                  az logout
                  az cache purge
                  az account clear
