name: CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: 5.x

            - name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.7
              with:
                  useConfigFile: true

            - name: Set Environment Variables
              run: |
                  echo "VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV
                  echo "STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV

            - name: Build
              env:
                  EXTEND_ESLINT: true
              run: |
                  yarn
                  yarn lint
                  yarn version --new-version ${{ env.VERSION }} --no-git-tag-version
                  yarn serverless:build --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}

            - name: Deploy
              env:
                  JWT_SECURITY_KEY: ${{ secrets.JWT_SECURITY_KEY }}
                  JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
                  JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
                  JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
                  MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
                  MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
                  MAILGUN_NO_REPLY: ${{ secrets.MAILGUN_NO_REPLY }}
                  SEED_EMAIL_ADDRESS: ${{secrets.SEED_EMAIL_ADDRESS }}
                  SEED_PASSWORD: ${{ secrets.SEED_PASSWORD }}
                  CLIENT_URL: ${{ secrets.CLIENT_URL }}
              run: |
                  yarn serverless:deploy --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}
                  yarn db:seed
