name: CI

on:
    push:
        branches:
            - '**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            EXTEND_ESLINT: true
            ENVIRONMENT: ${{ github.ref##*/ }}
            FAUNADB_SECRET: ${{ secrets.FAUNADB_SECRET }}
            JWT_SECURITYKEY: ${{ secrets.JWT_SECURITYKEY }}
            JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
            JWT_EXPIRESIN: ${{ secrets.JWT_EXPIRESIN }}
            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            MAILGUN_APIKEY: ${{ secrets.MAILGUN_APIKEY }}
            MAILGUN_NOREPLY: ${{ secrets.MAILGUN_NOREPLY }}
            SEED_EMAILADDRESS: ${{secrets.SEED_EMAILADDRESS }}
            SEED_PASSWORD: ${{ secrets.SEED_PASSWORD }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - run: yarn
            - run: yarn lint
            - run: yarn fauna
            - run: yarn serverless:build --stage ${{ github.ref##*/ }} --region ${{ secrets.AWS_REGION }}
            - run: yarn serverless:deploy --stage ${{ github.ref##*/ }} --region ${{ secrets.AWS_REGION }}
