name: CI

on:
    push:
        branches:
            - '**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: 5.x

            - name: Determine Version
              uses: gittools/actions/gitversion/execute@v0.9.7
              with:
                  useConfigFile: true

            - name: Set Environment Variables
              run: |
                  echo "VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV
                  echo "STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV

            - name: Build
              env:
                EXTEND_ESLINT: true
                # GA_MEASUREMENTID: {{ secrets[format('{0}_GA_MEASUREMENTID', env.STAGE)] }}
              run: |
                  yarn
                  yarn lint
                  yarn version --new-version ${{ env.VERSION }} --no-git-tag-version
                  yarn serverless:build --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}

            - name: Deploy
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                JWT_SECURITYKEY: ${{ secrets.JWT_SECURITYKEY }}
                JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
                JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
                JWT_EXPIRESIN: ${{ secrets.JWT_EXPIRESIN }}
                MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
                MAILGUN_APIKEY: ${{ secrets.MAILGUN_APIKEY }}
                MAILGUN_NOREPLY: ${{ secrets.MAILGUN_NOREPLY }}
                SEED_EMAILADDRESS: ${{secrets.SEED_EMAILADDRESS }}
                SEED_PASSWORD: ${{ secrets.SEED_PASSWORD }}
                # CLIENT_URL: ${{ secrets[format('{0}_CLIENT_URL', env.STAGE)] }}
              run: |
                  yarn serverless:deploy --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}
                  yarn db:seed
