name: CI

on:
    push:
        branches:
            - master

jobs:
    build:
        name: deploy
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            JWT_SECURITYKEY: ${{ secrets.JWT_SECURITYKEY }}
            JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
            SMTP_HOST: ${{ secrets.SMTP_HOST }}
            SMTP_PORT: ${{ secrets.SMTP_PORT }}
            SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
            SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD }}
            SMTP_NOREPLY: ${{ secrets.SMTP_NOREPLY }}
            SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
            SENTRY_ENVIRONMENT: ${{ secrets.AWS_STAGE }}
            SENTRY_RELEASE: ${{ secrets.GITHUB_SHA }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: yarn
            - run: yarn lint
            - run: yarn deploy --stage ${{ secrets.AWS_STAGE }} --region ${{ secrets.AWS_REGION }}
