name: CI

on:
    push:
        branches:
            - '**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            EXTEND_ESLINT: true

            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            JWT_SECURITYKEY: ${{ secrets.JWT_SECURITYKEY }}
            JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
            JWT_EXPIRESIN: ${{ secrets.JWT_EXPIRESIN }}

            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            MAILGUN_APIKEY: ${{ secrets.MAILGUN_APIKEY }}
            MAILGUN_NOREPLY: ${{ secrets.MAILGUN_NOREPLY }}

            SEED_EMAILADDRESS: ${{secrets.SEED_EMAILADDRESS }}
            SEED_PASSWORD: ${{ secrets.SEED_PASSWORD }}

            SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
            GA_MEASUREMENTID: ${{ secrets.GA_MEASUREMENTID }}

            CLIENT_URL: ${{ secrets.CLIENT_URL }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - run: echo "STAGE=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
            - run: echo "RELEASE=$(echo ${GITHUB_SHA})" >> $GITHUB_ENV

            - run: yarn
            - run: yarn lint

            - run: yarn serverless:build --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}
            - run: yarn serverless:deploy --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}

            - run: yarn db:seed

            - uses: getsentry/action-release@v1
              env:
                  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
                  SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
                  SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
              with:
                  environment: ${{ env.STAGE }}
                  version: ${{ env.RELEASE }}
                  sourcemaps: ./build
