name: CI

on:
    push:
        branches:
            - '**'

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        env:
            EXTEND_ESLINT: true

            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            JWT_SECURITYKEY: ${{ secrets.JWT_SECURITYKEY }}
            JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
            JWT_EXPIRESIN: ${{ secrets.JWT_EXPIRESIN }}

            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            MAILGUN_APIKEY: ${{ secrets.MAILGUN_APIKEY }}
            MAILGUN_NOREPLY: ${{ secrets.MAILGUN_NOREPLY }}

            SEED_EMAILADDRESS: ${{secrets.SEED_EMAILADDRESS }}
            SEED_PASSWORD: ${{ secrets.SEED_PASSWORD }}

            GA_MEASUREMENTID: ${{ secrets.GA_MEASUREMENTID }}

            CLIENT_URL: ${{ secrets.CLIENT_URL }}
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - uses: gittools/actions/gitversion/setup@v0.9.7
              with:
                  versionSpec: 5.x

            - uses: gittools/actions/gitversion/execute@v0.9.7
              with:
                  useConfigFile: true

            - run: echo "STAGE=$(echo ${{ env.GITVERSION_ESCAPEDBRANCHNAME }})" >> $GITHUB_ENV
            - run: echo "VERSION=$(echo ${{ env.GITVERSION_SEMVER }})" >> $GITHUB_ENV

            - run: yarn version --new-version ${{ env.VERSION }} --no-git-tag-version

            - run: yarn
            - run: yarn lint

            - run: yarn serverless:build --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}
            - run: yarn serverless:deploy --stage ${{ env.STAGE }} --region ${{ secrets.AWS_REGION }}

            - run: yarn db:seed
