name: Playwright Tests

on:
    workflow_dispatch:

env:
    HUSKY: 0
    NEXT_TELEMETRY_DISABLED: 1

jobs:
    test:
        runs-on: ubuntu-latest
        timeout-minutes: 20
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'

            - name: Run Playwright tests
              run: |
                  npm ci
                  npm run playwright:install
                  npm run playwright:test
              env:
                  PLAYWRIGHT_TEST_BASE_URL: ${{ vars.URL }}

            - name: Upload Playwright report
              uses: actions/upload-artifact@v4
              if: ${{ !cancelled() }}
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 10
