# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Preview Build and Deploy

on:
    push:
        branches:
            - 'feature/**'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0
              with:
                  versionSpec: '5.x'

            - name: Determine Version
              id: gitversion
              uses: gittools/actions/gitversion/execute@v0
              with:
                  useConfigFile: true

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
                  cache: yarn

            - name: yarn install, build, and test
              env:
                  NEXT_PUBLIC_GITVERSION_SEMVER: ${{ steps.gitversion.outputs.semVer }}
                  NEXT_TELEMETRY_DISABLED: 1
              run: |
                  yarn install --frozen-lockfile
                  yarn lint
                  yarn build
                  yarn test

            - name: Move static folders into dynamic folder
              run: |
                  cp -r ./public ./.next/standalone
                  cp -r ./prisma ./.next/standalone
                  cp -r ./.next/static ./.next/standalone/.next/static
                  rm ./.next/standalone/package.json

            - name: Create artifact zip
              run: zip -r ../../standalone.zip ./* ./.next/*
              working-directory: ./.next/standalone

            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v3
              with:
                  name: halcyon-web
                  path: ./standalone.zip

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: Preview
            url: ${{ vars.URL }}

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v3
              with:
                  name: halcyon-web

            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                  app-name: ${{ secrets.AZUREAPPSERVICE_APPNAME }}
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
                  package: ./standalone.zip
