name: Remove

on:
    delete:
        branches:
            - '**'

jobs:
    remove-resources:
        runs-on: ubuntu-latest
        env:
            FAUNADB_SECRET: ${{ secrets.FAUNADB_SECRET }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - run: echo "ENVIRONMENT=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

            - run: yarn
            - run: yarn db:remove
            - run: yarn serverless:remove --stage ${{ env.ENVIRONMENT }} --region ${{ secrets.AWS_REGION }}
