name: Serverless

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            JWT_SECURITYKEY: ${{ secrets.JWT_SECURITYKEY }}
            JWT_AUDIENCE: ${{ secrets.JWT_AUDIENCE }}
            JWT_ISSUER: ${{ secrets.JWT_ISSUER }}
            MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
            MAILGUN_PASSWORD: ${{ secrets.MAILGUN_PASSWORD }}
            MAILGUN_NOREPLY: ${{ secrets.MAILGUN_NOREPLY }}
            SEED_EMAILADDRESS: ${{ secrets.SEED_EMAILADDRESS }}
            SEED_PASSWORD: ${{ secrets.SEED_PASSWORD }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - run: yarn install
            - run: yarn lint
            - run: npx serverless deploy
